name: Deploy Prod on Firebase Hosting

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Latest Version
        uses: actions/checkout@v4

      - name: Deploy to Firebase
        uses: docker://w9jds/firebase-action:v14.10.1
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_HOSTING_KEY }}
